name: 'data_contracts_demo'
version: '1.0.0'
config-version: 2

profile: 'data_contracts_demo'

model-paths: ["models"]
seed-paths: ["seeds"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_contracts_demo:
    producer:
      +materialized: table
    consumer:
      +materialized: table
